dead_beef: dead_beef.cpp
	gcc -o dead_beef dead_beef.cpp -lbcm2835 -lstdc++
	
transducer_test: transducer_test.cpp
	gcc -o transducer_test transducer_test.cpp -lbcm2835 -lstdc++

monitor: monitor.cpp
	gcc -o monitor monitor.cpp -lbcm2835 -lstdc++
	
clean:
	$(RM) dead_beef
	$(RM) transducer_test
	$(RM) monitor
